### ISSUE TITLE
[2pts] Setting up the Database

### ISSUE THREAD

**Issue by celineMaina** [celineMaina/Cloud-Resume-API#3]
## Task
- [ ] Choose suitable NoSQL database. In this project, I will use Amazon DynamoDB.
- [ ] Create a table to store resume data.
- [ ] Add data into the table.

### Description
- Setting up a Database with a table to hold our resume data.
